Dockerfile

Update systemd and systemd-libs

DEPLOY-356 CVE-2018-1049 RHSA-2018:0260

---

build-prep.sh
build.properties

DEPLOY-416

---

build-prep.sh
build.properties

Java 10 compatible build (on Java 8 branch).

DEPLOY-416 java 8

---

README.md
build.properties

Updated guidelines. Also made it pass markdownlint.

DEPLOY-275: Assure Guidelines are clear on use of images wrt immutability

---

Dockerfile
build-prep.sh
build.properties

Build is green in Quay https://quay.io/repository/alfresco/alfresco-base-java?tab=tags

DEPLOY-483 Medium security issues. Fix shellcheck errors.

---

all-stages.sh
build-prep.sh
build.properties
hack/uploader.sh
src/Dockerfile

Branch built via new method:
~~https://bamboo.alfresco.com/bamboo/browse/PS-DBJIR0-JOB1-1/log~~
~~https://bamboo.alfresco.com/bamboo/browse/PS-DBJIR0-JOB1-3/log~~
~~https://quay.io/repository/alfresco/alfresco-base-java/manifest/sha256:01ef6db3244a719690c968b2a6595412f2fb9c8597cd9fe715fe7c752739034e~~
https://bamboo.alfresco.com/bamboo/browse/PS-DBJIR0-JOB1-4/log
https://quay.io/repository/alfresco/alfresco-base-java/manifest/sha256:7625782b23de120f04eb285a0cc796a97403e218a8507079d7aef9812d5df8b1
This is a stepping stone on the way to
a) simpler builds
2) multiple Java versions
iii) de-bambooification

DEPLOY-546 CentOS 7.5; Java 8u181; Use --build-arg for Java file; Simpler Build Script

---

Dockerfile

Suggestion to set UTF-8 as default locale.

ALF-22013 Fix UTF-8 as default locale

---

Dockerfile

Updated the Dockerfile by adding 'yum clean all'.

Issue#23-Reduce image size by adding 'yum clean all'

---

Dockerfile

AUTH-456: Added keytool to the path.

---

Dockerfile

Fixed base java vulnerabilities.

DEPLOY-886: Fixed base java vulnerabilities

---

Dockerfile

-Add sqlite-3.7.17-8.el7_7.1 to address CVE-2019-13734

[DEPLOY-924] Security Vulnerability in Base Java image

---

.travis.yml
Dockerfile

fixes ACS-1199 and adds support for Centos 8

ACS-1199 Fix vulnerabilities in alfresco-java-base image

---

.github/dependabot.yml
.travis.yml
Dockerfile
README.md
centos-7/Dockerfile
centos-8/Dockerfile

Split multi stage Dockerfile into seperate ones and adjusted dependabot config to update CentOS 7 and 8 seperately

ACS-1210 Support CentOS dependabot updates

---

centos-7/Dockerfile
centos-8/Dockerfile

Fixes https://access.redhat.com/errata/RHSA-2021:0670

OPSEXP-810 update BIND for vulnerability

---

Dockerfile
centos-7/Dockerfile
centos-8/Dockerfile

Updating vulnerabilities reported by quay.io for DEVOPS-25
Checks running green on quay https://quay.io/repository/alfresco/alfresco-base-java?tab=tags

DEVOPS-25 update vulns

---

Dockerfile
centos-7/Dockerfile
centos-8/Dockerfile

* broken in commit a2bf7bad05147e77e5122584dfc6c36bc0dbf7ff
* fixes #60

Fix UTF-8 encoding on Centos 8

---

.travis.yml
Dockerfile
README.md

Fix JDK vulnerabilities updating to 8.0.302 and 11.0.12
Ref OPSEXP-959

OPSEXP-959 fixed jdk vulns

---

Dockerfile
centos-7/Dockerfile
debian-10/Dockerfile

Ref OPSEXP-1037
Defaulting to using static symlink as it's not possible with Dockerfile to set ENV dyanmically :(

OPSEXP-1037 set JAVA_HOME for reuse in child images

---

.travis.yml
Dockerfile
README.md
ubi-8/Dockerfile

Updated to new versions where possible and kept only major in the tag as it's not the same across distros

OPSEXP-1142 Update to OpenJDK 11.0.13

---

.github/dependabot.yml

OPSEXP-1236: fix and harden dependabot config

---

.github/workflows/main.yml
Dockerfile

OPSEXP-1257 build alpine base image

---

README.md

OPSEXP-1294
Preview: https://github.com/Alfresco/alfresco-docker-base-java/blob/OPSEXP-1294-readme-rewrite/README.md

OPSEXP-1294 README rewrite with emphasis on how to use it

---

.github/workflows/main.yml
Dockerfile
README.md

OPSEXP-1738: alpine removal

---

.github/workflows/main.yml
Dockerfile

Ref: OPSEXP-2136 also add some tests before pushing

OPSEXP-2136: Set env locales properly for Rocky Linux 8

---

.github/dependabot.yml
.github/workflows/main.yml
Dockerfile

OPSEXP-2432 Always use latest rockylinux images

---

Dockerfile

OPSEXP-2432 Build with latest RL 9.x

---

.github/workflows/main.yml

OPSEXP-2149 Fixup release workflow

---

.github/workflows/main.yml
.github/workflows/pre-commit.yml

OPSEXP-2149 Do not build images without Docker changes

---

.github/workflows/main.yml
Dockerfile
README.md

OPSEXP-2693 Drop Centos 7 support

---

.github/workflows/main.yml

OPSEXP-2949 Add JRE 21
